### ISSUE TITLE
Arrow in Dog font diagram in wrong place

### ISSUE THREAD

**Issue by mbakeranalecta** [mbakeranalecta/structuredwritingbook#61]
It should be relating the font names in both boxes.

**Comment by rlhamilton** [comment]
Do you mean the arrows on the left-hand side of that figure (and I assume you mean Figure 3.3 on page 24)?

**Comment by mbakeranalecta** [comment]
Yes, the arrows on the left side were intended to show that the font name is the piece of information that is used to match the two information sets to each other. I used arrows the same way in the merge diagram, and you replaced them by bolding the key phrase in both examples. I'm not sure if that approach works here because there is other formatted text in this example and it might not be clear what the bolding of the font name meant.

**Comment by mbakeranalecta** [comment]
Addressed in https://github.com/mbakeranalecta/structuredwritingbook/pull/76/commits/0ce518432f369a9d579362b8b7a0e20fb8aeda5c
